name: C-ray CI

on: [pull_request]

jobs:
  macos:
    name: macOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: build
      run: make
  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: cmake .
    - name: build
      run: make
  winbuild:
      name: Windows Build
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v1
      - uses: warrenbuckley/Setup-MSBuild@v1
      - name: cmake
        run: cmake -G "Visual Studio 16 2019" -A x64 .
      - name: build
        run: msbuild c-ray.sln /p:Configuration=Release /p:WarningLevel=0
